global:
  tls:
    enabled: false
  logLevel: debug
server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
client:
  enabled: true
  grpc: true
connectInject:
  enabled: true
  default: true
  replicas: 1
  cni:
    enabled: true
    cniBinDir: /home/kubernetes/bin
ui:
  enabled: true
controller:
  enabled: true
