global:
  name: consul
  datacenter: dc1
  logLevel: "debug"
  imagePullSecrets:
    - name: 15962412-openshift-pull-secret
  openshift:
    enabled: true
server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
client:
  enabled: true
  grpc: true
connectInject:
  enabled: true
  default: false 
  replicas: 1
  cni:
    enabled: true
    logLevel: debug
    cniBinDir: /var/lib/cni/bin
    cniNetDir: /etc/kubernetes/cni/net.d
dns:
  enabled: false
ui:
  enabled: true
controller:
  enabled: true
