global:
  logLevel: "debug"
  tls:
    enabled: false
server:
  replicas: 1
connectInject:
  enabled: true
  default: true
  replicas: 1
dns:
  enabled: false
ui:
  enabled: true
  service:
    enabled: true
controller:
  enabled: true
