global:
  name: consul
  datacenter: dc1
  logLevel: "debug"
  imagePullSecrets:
    - name: openshift-pull-secret
  openshift:
    enabled: true
server:
  enabled: true
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
client:
  enabled: false
  grpc: true
connectInject:
  enabled: true
  default: true
  replicas: 1
  cni:
    enabled: true
    logLevel: info
    multus: true
    cniBinDir: /var/lib/cni/bin
    cniNetDir: /etc/kubernetes/cni/net.d
dns:
  enabled: true
ui:
  enabled: true
controller:
  enabled: true
