global:
  enabled: false
  name: consul
  domain: consul
  enterpriseLicense:
   secretName: 'consul-ent-license'
   secretKey: 'key'
  imagePullSecrets: []
  datacenter: us-west2
  tls:
    enabled: false
  enableConsulNamespaces: true
  federation:
    enabled: false
 
externalServers:
  enabled: true
  hosts: ["external.consul.server"] 
  httpsPort: 8500
  tlsServerName: null
  useSystemRoots: false
  k8sAuthMethodHost: null

connectInject:
  enabled: true
  default: false
  healthChecks:
    enabled: false
    reconcilePeriod: "1m"
  logLevel: "info"
  resources:
    requests:
      memory: "100Mi"
      cpu: "1"
    limits:
      memory: "100Mi"
      cpu: "1"
  namespaceSelector: null
  k8sAllowNamespaces: ["sbx1", "consul"]
  k8sDenyNamespaces: []
  cni:
    enabled: true
    logLevel: info
    cniBinDir: "/home/kubernetes/bin"
    cniNetDir: "/etc/cni/net.d"
  transparentProxy:
    defaultEnabled: false #to enable service mesh this should be set to true
