---
# Consul connect requires you to have a service, even if you're connecting a job to the mesh
apiVersion: v1
kind: Service
metadata:
  # This name will be the service name in Consul.
  name: test-job
  namespace: service-mesh
spec:
  selector:
    app: test-job
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: test-job
#   namespace: service-mesh
#   labels:
#     app: test-job
#   annotations:
#     "consul.hashicorp.com/connect-inject": "true"
#     #"consul.hashicorp.com/transparent-proxy": "false"
# spec:
#   template:
#     spec:
#       containers:
#       - name: test-job
#         image: alpine:latest
#         command:
#           - /bin/bash
#           - -c
#           - |
#             echo "Started test job"
#             sleep 10
#             echo "Started test job"
#       restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-job 
  namespace: service-mesh
spec:
  # Run every 10 minutes or so
  # TODO: figure out our desired schedule
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          name: test-job
          labels:
            app: test-job
          annotations:
            "consul.hashicorp.com/connect-inject": "true"
            # To kill the dataplane sidecar, we have to set the container uid to dataplane uid.
            # This setup messes with tproxy establishing a stream with upstream services,
            # so we will explicitly set upstreams until /quitquitquit envoy gracefully terminates the sidecar
            "consul.hashicorp.com/transparent-proxy": "false"
            "consul.hashicorp.com/connect-service-upstreams": "mesh-sli-comms-server:3000"
        spec:
          shareProcessNamespace: true
          serviceAccountName: test-job
          restartPolicy: OnFailure
          containers:
            - name: test-job
              image: alpine:latest
              imagePullPolicy: Always
              # Dataplane doesn't gracefully shutdown after envoy shutdown process
              # until https://github.com/hashicorp/consul-k8s/issues/1791 gets fixed,
              # we kill the dataplane container
              command:
                - /bin/bash
                - -c
                - |
                  echo "Started test job"
                  sleep 10
                  echo "Started test job"
              securityContext:
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                # to send SIGTERM to shutdown dataplane sidecar
                capabilities:
                  drop:
                    - all 
                  add: ["KILL"]
              resources:
                limits:
                  cpu: 50m
                  memory: 150Mi
                requests:
                  cpu: 50m
 
