---
# Consul connect requires you to have a service, even if you're connecting a job to the mesh
apiVersion: v1
kind: Service
metadata:
  # This name will be the service name in Consul.
  name: test-job
  namespace: service-mesh
spec:
  selector:
    app: test-job
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
---
apiVersion: batch/v1
kind: Job
metadata:
   name: test-job
   namespace: service-mesh
   labels:
     app: test-job
   annotations:
     "consul.hashicorp.com/connect-inject": "true"
     "consul.hashicorp.com/transparent-proxy": "false"
spec:
  template:
    spec:
      containers:
      - name: test-job
        image: alpine:latest
        command:
          - /bin/bash
          - -c
          - |
            echo "Started test job"
            sleep 10
            echo "Started test job"
      restartPolicy: Never

